name: Build Therapy Dog Connect

on:
  push:
    branches:
      - '**' # Trigger on pushes to any branch
  pull_request:
    branches:
      - '**' # Trigger for any PR targeting any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build project
        env:
          CI: false # Prevent treating warnings as errors
          GENERATE_SOURCEMAP: true
        run: npm run build

      - name: Test project
        run: npm test

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./build # Path to the build output
