name: Deploy Therapy Dog Connect to S3

on:
  workflow_run:
    workflows:
      - Build Therapy Dog Connect
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: ./build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          if [ "${{ github.ref_name }}" = "dev" ]; then
            echo "Deploying to Dev environment..."
            aws s3 sync build/ s3://dev-therapydogconnect --delete
          elif [ "${{ github.ref_name }}" = "staging" ]; then
            echo "Deploying to Staging environment..."
            aws s3 sync build/ s3://staging-therapydogconnect --delete
          elif [ "${{ github.ref_name }}" = "main" ]; then
            echo "Deploying to Production environment..."
            aws s3 sync build/ s3://prod-therapydogconnect --delete
          else
            echo "Branch not configured for deployment."
            exit 1
          fi
