name: Deploy Therapy Dog Connect

on:
  workflow_run:
    workflows:
      - Build Therapy Dog Connect
    types:
      - completed

jobs:
  deploy:
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' && 
      (github.event.workflow_run.head_branch == 'main' || 
       github.event.workflow_run.head_branch == 'dev' || 
       github.event.workflow_run.head_branch == 'staging') }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Create Amplify Configuration
      - name: Create Amplify Configuration
        env:
          AWS_PROJECT_REGION: ${{ secrets.AWS_PROJECT_REGION }}
          AWS_COGNITO_IDENTITY_POOL_ID: ${{ secrets.AWS_COGNITO_IDENTITY_POOL_ID }}
          AWS_COGNITO_REGION: ${{ secrets.AWS_COGNITO_REGION }}
          AWS_USER_POOLS_ID: ${{ secrets.AWS_USER_POOLS_ID }}
          AWS_USER_POOLS_WEB_CLIENT_ID: ${{ secrets.AWS_USER_POOLS_WEB_CLIENT_ID }}
        run: node create-amplify-config.js

      # Step 5: Build the project
      - name: Build project
        env:
          CI: false
        run: npm run build

      # Step 6: Deploy to S3
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          if [ "${{ github.event.workflow_run.head_branch }}" = "dev" ]; then
            aws s3 sync build/ s3://dev-therapydogconnect --delete
          elif [ "${{ github.event.workflow_run.head_branch }}" = "staging" ]; then
            aws s3 sync build/ s3://staging-therapydogconnect --delete
          elif [ "${{ github.event.workflow_run.head_branch }}" = "main" ]; then
            aws s3 sync build/ s3://prod-therapydogconnect --delete
          else
            echo "Branch not configured for deployment."
            exit 1
          fi
