name: Deploy Therapy Dog Connect

on:
  workflow_run:
    workflows:
      - Build Therapy Dog Connect
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Extract Branch Name from Workflow Run
      - name: Extract Branch Name
        id: extract
        run: |
          REF=${{ github.event.workflow_run.head_branch || github.ref_name }}
          echo "SANITIZED_BRANCH_NAME=${REF//[^a-zA-Z0-9_-]/-}" >> $GITHUB_ENV

      # Step 2: Download the build artifact
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact-${{ env.SANITIZED_BRANCH_NAME }}

      # Step 3: Deploy to S3
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          if [ "${{ github.ref_name }}" = "dev" ]; then
            aws s3 sync build/ s3://dev-therapydogconnect --delete
          elif [ "${{ github.ref_name }}" = "staging" ]; then
            aws s3 sync build/ s3://staging-therapydogconnect --delete
          elif [ "${{ github.ref_name }}" = "main" ]; then
            aws s3 sync build/ s3://prod-therapydogconnect --delete
          else
            echo "Branch not configured for deployment."
            exit 1
          fi
